filter:
  excluded_paths:
    - 'vendor/*'
    - '.github/*'
    - 'examples/*'
    - 'php-tests/*'
  paths:
    - 'php-src/*'

build:
  environment:
    php:
      version: '8.1'
  dependencies:
    before:
      - wget -O composer.phar https://getcomposer.org/composer.phar
      - chmod +x composer.phar
      - ./composer.phar install
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: WITH_TEST_ENV=1 vendor/bin/tester -C -j 30 php-tests --coverage-src php-src/ --coverage php-tests/temp/clover.xml
            coverage:
              file:  php-tests/temp/clover.xml
              format: php-clover

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      ternary_operator:
        in_short_version: false
      other:
        after_type_cast: true
